apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: otcgvxayk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: otcgvxayk-nodejs 
  name: otcgvxayk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: otcgvxayk-nodejs 
